services:
  - type: web
    name: rancom-technologies
    runtime: docker
    repo: https://github.com/Lightining29/ransom.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
